const MYPAGE = {
  LOAD_MYCONTENTS_REQUEST: "LOAD_MYCONTENTS_REQUEST",
  LOAD_MYCONTENTS_SUCCESS: "LOAD_MYCONTENTS_SUCCESS",
  LOAD_MYCONTENTS_FAILURE: "LOAD_MYCONTENTS_FAILURE",

  LOAD_MY_ZZIM_LIST_REQUEST: "LOAD_MY_ZZIM_LIST_REQUEST",
  LOAD_MY_ZZIM_LIST_SUCCESS: "LOAD_MY_ZZIM_LIST_SUCCESS",
  LOAD_MY_ZZIM_LIST_FAILURE: "LOAD_MY_ZZIM_LIST_FAILURE",

  LOAD_MY_OWNER_ITEM_REQUEST: "LOAD_MY_OWNER_ITEM_REQUEST",
  LOAD_MY_OWNER_ITEM_SUCCESS: "LOAD_MY_OWNER_ITEM_SUCCESS",
  LOAD_MY_OWNER_ITEM_FAILURE: "LOAD_MY_OWNER_ITEM_FAILURE",

  LOAD_MY_RENTAL_ITEM_REQUEST: "LOAD_MY_RENTAL_ITEM_REQUEST",
  LOAD_MY_RENTAL_ITEM_SUCCESS: "LOAD_MY_RENTAL_ITEM_SUCCESS",
  LOAD_MY_RENTAL_ITEM_FAILURE: "LOAD_MY_RENTAL_ITEM_FAILURE",
};

export default MYPAGE;
