const POST = {
  LOAD_POSTS_REQUEST: "LOAD_POSTS_REQUEST",
  LOAD_POSTS_SUCCESS: "LOAD_POSTS_SUCCESS",
  LOAD_POSTS_FAILURE: "LOAD_POSTS_FAILURE",

  LOAD_POST_REQUEST: "LOAD_POST_REQUEST",
  LOAD_POST_SUCCESS: "LOAD_POST_SUCCESS",
  LOAD_POST_FAILURE: "LOAD_POST_FAILURE",

  ADD_POST_REQUEST: "ADD_POST_REQUEST",
  ADD_POST_SUCCESS: "ADD_POST_SUCCESS",
  ADD_POST_FAILURE: "ADD_POST_FAILURE",

  UPDATE_POST_REQUEST: "UPDATE_POST_REQUEST",
  UPDATE_POST_SUCCESS: "UPDATE_POST_SUCCESS",
  UPDATE_POST_FAILURE: "UPDATE_POST_FAILURE",

  REMOVE_POST_REQUEST: "REMOVE_POST_REQUEST",
  REMOVE_POST_SUCCESS: "REMOVE_POST_SUCCESS",
  REMOVE_POST_FAILURE: "REMOVE_POST_FAILURE",

  UPLOAD_IMAGES_REQUEST: "UPLOAD_IMAGES_REQUEST",
  UPLOAD_IMAGES_SUCCESS: "UPLOAD_IMAGES_SUCCESS",
  UPLOAD_IMAGES_FAILURE: "UPLOAD_IMAGES_FAILURE",

  REMOVE_IMAGE: "REMOVE_IMAGE",

  REMOVE_IMAGES_REQUEST: "REMOVE_IMAGES_REQUEST",
  REMOVE_IMAGES_SUCCESS: "REMOVE_IMAGES_SUCCESS",
  REMOVE_IMAGES_FAILURE: "REMOVE_IMAGES_FAILURE",

  ADD_COMMENT_REQUEST: "ADD_COMMENT_REQUEST",
  ADD_COMMENT_SUCCESS: "ADD_COMMENT_SUCCESS",
  ADD_COMMENT_FAILURE: "ADD_COMMENT_FAILURE",

  ZZIM_POST_REQUEST: "ZZIM_POST_REQUEST",
  ZZIM_POST_SUCCESS: "ZZIM_POST_SUCCESS",
  ZZIM_POST_FAILURE: "ZZIM_POST_FAILURE",

  NOT_ZZIM_POST_REQUEST: "NOT_ZZIM_POST_REQUEST",
  NOT_ZZIM_POST_SUCCESS: "NOT_ZZIM_POST_SUCCESS",
  NOT_ZZIM_POST_FAILURE: "NOT_ZZIM_POST_FAILURE",

  APPLY_RENTAL_REQUEST: "APPLY_RENTAL_REQUEST",
  APPLY_RENTAL_SUCCESS: "APPLY_RENTAL_SUCCESS",
  APPLY_RENTAL_FAILURE: "APPLY_RENTAL_FAILURE",
};

export default POST;
