/* 로그인 액션 */
const USER = {
  LOG_IN_REQUEST: "LOG_IN_REQUEST",
  LOG_IN_SUCCESS: "LOG_IN_SUCCESS",
  LOG_IN_FAILURE: "LOG_IN_FAILURE",

  /* 카카오 로그인 액션 */
  KAKAO_LOG_IN_REQUEST: "KAKAO_LOG_IN_REQUEST",
  KAKAO_LOG_IN_SUCCESS: "KAKAO_LOG_IN_SUCCESS",
  KAKAO_LOG_IN_FAILURE: "KAKAO_LOG_IN_FAILURE",

  /* 네이버 로그인 액션 */
  NAVER_LOG_IN_REQUEST: "NAVER_LOG_IN_REQUEST",
  NAVER_LOG_IN_SUCCESS: "NAVER_LOG_IN_SUCCESS",
  NAVER_LOG_IN_FAILURE: "NAVER_LOG_IN_FAILURE",

  /* 로그인 확인 액션 */
  LOAD_USER_INFO_REQUEST: "LOAD_USER_INFO_REQUEST",
  LOAD_USER_INFO_SUCCESS: "LOAD_USER_INFO_SUCCESS",
  LOAD_USER_INFO_FAILURE: "LOAD_USER_INFO_FAILURE",

  /* 로그아웃 액션 */
  LOG_OUT_REQUEST: "LOG_OUT_REQUEST",
  LOG_OUT_SUCCESS: "LOG_OUT_SUCCESS",
  LOG_OUT_FAILURE: "LOG_OUT_FAILURE",

  /* 회원가입 액션 */
  SIGN_UP_REQUEST: "SIGN_UP_REQUEST",
  SIGN_UP_SUCCESS: "SIGN_UP_SUCCESS",
  SIGN_UP_FAILURE: "SIGN_UP_FAILURE",

  LOAD_TOKEN_REQUEST: "LOAD_TOKEN_REQUEST",
  LOAD_TOKEN_SUCCESS: "LOAD_TOKEN_SUCCESS",
  LOAD_TOKEN_FAILURE: "LOAD_TOKEN_FAILURE",

  /* 닉네임 변경 액션 */
  CHANGE_NICKNAME_REQUEST: "CHANGE_NICKNAME_REQUEST",
  CHANGE_NICKNAME_SUCCESS: "CHANGE_NICKNAME_SUCCESS",
  CHANGE_NICKNAME_FAILURE: "CHANGE_NICKNAME_FAILURE",

  UPLOAD_PROFILE_IMAGE_REQUEST: "UPLOAD_PROFILE_IMAGE_REQUEST",
  UPLOAD_PROFILE_IMAGE_SUCCESS: "UPLOAD_PROFILE_IMAGE_SUCCESS",
  UPLOAD_PROFILE_IMAGE_FAILURE: "UPLOAD_PROFILE_IMAGE_FAILURE",
};

export default USER;
